AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Repo:
    Type: String
    Default: aws-example
  Owner:
    Type: String
  InfraSourceBranch:
    Type: String
    Default: master
  OAuthToken:
    NoEcho: true
    Type: String
  PipelineName:
    Type: String
  ScanImage:
    Type: String

Resources:
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}"

  CodePipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CodePipelineBucket
      PolicyDocument: 
        Statement: 
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
            Resource:
              - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-${AWS::AccountId}"
              - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-${AWS::AccountId}/*"
            Principal:
              Service: "codepipeline.amazonaws.com"
            Effect: "Allow"      

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        -
          Action: 
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Action:
                  - s3:PutObject
                  - s3:GetBucketPolicy
                  - s3:GetObject
                  - s3:ListBucket
                Effect: Allow
                Resource: '*'
              - 
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
              -
                Action:
                  - ecr:CreateRepository
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Effect: Allow
                Resource: '*'

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    DependsOn: CodePipelineBucket
    Properties: 
      Name: !Join [ "-", [ docker, build, !Ref 'AWS::AccountId' ] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:3.0'
        PrivilegedMode: true
        EnvironmentVariables:
          -
            Name: AWS_DEFAULT_REGION
            Value: !Ref 'AWS::Region'
          -
            Name: AWS_ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
          -
            Name: SCAN_IMAGE_NAME
            Value: !Ref ScanImage
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: vulnerability-scan/buildspec.yml

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: 
             - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - s3:PutObject
                Effect: Allow
                Resource: 
                  - "arn:aws:s3:::*"
              -
                Action:
                  - codepipeline:*
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - cloudformation:Describe*
                  - cloudFormation:List*
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Effect: Allow
                Resource: '*'

  DockerBuildCodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref PipelineName
      ArtifactStore: 
        Location: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
        Type: S3
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        -
          Name: Source
          Actions: 
            -
              Name: InfraSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              InputArtifacts: []
              OutputArtifacts:
                - Name: InfraSource
              Configuration:
                Owner: !Ref Owner
                Repo: !Ref Repo
                Branch: !Ref InfraSourceBranch
                OAuthToken: !Ref OAuthToken
              RunOrder: 1
        -
          Name: Build
          Actions:
            - 
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: InfraSource
              Configuration:
                ProjectName: !Ref CodeBuildProject
                PrimarySource: InfraSource
              RunOrder: 2


