AWSTemplateFormatVersion: '2010-09-09'


Resources:
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: AwsExecRead
      BucketName: !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-repogitory ] ]
    DeletionPolicy: Delete

  CodePipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CodePipelineBucket
      PolicyDocument: 
        Statement: 
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
            Resource:
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-repogitory ] ] ] ]
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-repogitory ] ], '/*' ] ]
            Principal: "*"
            Effect: "Allow"

  CodePipelineLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: AwsExecRead
      BucketName: !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-logs ] ]
    DeletionPolicy: Delete

  CodePipelineLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CodePipelineLogBucket
      PolicyDocument: 
        Statement: 
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
            Resource:
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-logs ] ] ] ]
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ !Ref 'AWS::AccountId', codepipeline-logs ] ], '/*' ] ]
            Principal: "*"
            Effect: "Allow"

