AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  UserID:
    Type: String

Resources:
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
    DeletionPolicy: Delete

  CodePipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CodePipelineBucket
      PolicyDocument: 
        Statement: 
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
            Resource:
              - !Sub 'arn:aws:s3:::codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
              - !Sub 'arn:aws:s3:::codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}/*'
            Principal:
              Service: "codepipeline.amazonaws.com"
            Effect: "Allow"
