AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  UserID:
    Type: String

Resources:
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join [ "-", [ codepipeline, !Ref 'AWS::Region', !Ref 'AWS::AccountId' ] ]
    DeletionPolicy: Delete

  CodePipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CodePipelineBucket
      PolicyDocument: 
        Statement: 
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
            Resource:
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ codepipeline, !Ref 'AWS::Region', !Ref 'AWS::AccountId' ] ] ] ]
              - !Join [ "", [ 'arn:aws:s3:::', !Join [ "-", [ codepipeline, !Ref 'AWS::Region', !Ref 'AWS::AccountId' ] ], "/*" ] ]
            Principal:
              CanonicalUser: !Ref UserID
            Effect: "Allow"
