AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Repo:
    Type: String
    Default: aws-example
  Owner:
    Type: String
  AppSourceBranch:
    Type: String
    Default: master
  DockerSourceBranch:
    Type: String
    Default: master
  OAuthToken:
    NoEcho: true
    Type: String
  PipelineName:
    Type: String
  DockerImageName:
    Type: String
    Default: hello-world

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        -
          Action: 
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Action:
                  - s3:PutObject
                  - s3:GetBucketPolicy
                  - s3:GetObject
                  - s3:ListBucket
                Effect: Allow
                Resource: '*'
              - 
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
              -
                Action:
                  - ecr:CreateRepository
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Effect: Allow
                Resource: '*'
  
  ECRRepogitory:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref DockerImageName

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Name: !Join [ "-", [ docker, build, !Ref 'AWS::AccountId' ] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'adoptopenjdk:11-hotspot-bionic'
        PrivilegedMode: true
        EnvironmentVariables:
          -
            Name: AWS_DEFAULT_REGION
            Value: !Ref 'AWS::Region'
          -
            Name: AWS_ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
          -
            Name: IMAGE_REPO_NAME
            Value: !Ref DockerImageName
          -
            Name: IMAGE_TAG
            Value: latest
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: adoptopenjdk-jib/buildspec.yml

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: 
             - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - s3:PutObject
                Effect: Allow
                Resource: 
                  - "arn:aws:s3:::*"
              -
                Action:
                  - codepipeline:*
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - cloudformation:Describe*
                  - cloudFormation:List*
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Effect: Allow
                Resource: '*'

  DockerBuildCodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref PipelineName
      ArtifactStore: 
        Location: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
        Type: S3
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        -
          Name: Source
          Actions: 
            -
              Name: DockerSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              InputArtifacts: []
              OutputArtifacts:
                - Name: DockerSource
              Configuration:
                Owner: !Ref Owner
                Repo: !Ref Repo
                Branch: !Ref DockerSourceBranch
                OAuthToken: !Ref OAuthToken
              RunOrder: 1
            -
              Name: AppSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              InputArtifacts: []
              OutputArtifacts:
                - Name: AppSource
              Configuration:
                Owner: !Ref Owner
                Repo: mecab-java-api-server
                Branch: !Ref AppSourceBranch
                OAuthToken: !Ref OAuthToken
              RunOrder: 1
        -
          Name: Build
          Actions:
            - 
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: DockerSource
                - Name: AppSource
              OutputArtifacts:
                - Name: BuildResult 
              Configuration:
                ProjectName: !Ref CodeBuildProject
                PrimarySource: DockerSource
              RunOrder: 2


