version: 0.2

# env:

phases:
  install: 
    commands:
      - npm install -g typescript
      - tsc -v

  # pre_build: 
  #   commands: 

  build: 
    commands:
      - cd typescript-code-build/app/src && tsc main.ts
      - cd ../../ && aws cloudformation package --template cloudformation/template.yml --s3-bucket codepipeline-us-east-1-653810325336 --output-template-file package-template.yml
  
artifacts:
  files:
    - app/src/*.js
    - package-template.yml
  discard-paths: no
  base-directory: typescript-code-build

