packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true

engineStrict: true

overrides:
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@types/node': ^24.0.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  diff@<8.0.3: '>=8.0.3'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
