packages:
  - './common/cognito-singin'
  - './cognito/authorizer-example/api'
  - './cognito/authorizer-example/front'
  - './cognito/cognito-admin/app'
  - './cognito/cognito-admin/infra'
  - './cognito/cognito-saml-next-js/infra/aws'
  - './cognito/cognito-saml-next-js/infra/azuread'
  - './cognito/cognito-saml-next-js/webapp'
  - './cognito/tiny-device-flow'
  - './cognito/tiny-device-flow/pages'
  - './cognito/trigger-examples'
  - './lambda/deno-lambda'
  - './amplify/amplify_nextapp'
  - './amplify/amplify-cdk/app'
  - './amplify/amplify-cdk/infra'
  - './infra/s3'
  - './cloud9'
  - './infra/ecs'
  - './codebuild/custom-image-test'
  - './codebuild/codebuild-webhook-project/infra'
  - './lambda/apollo-server-url'
  - './lambda/apollo-server-api-gateway'
  - './lambda/eventbridge-lambda'
  - './lambda/lambda-examples'
  - './codepipeline/adoptium-temurin-jib/infra'
  - './codepipeline/codebuild-custom-image/java-adopt-base/infra'
  - './codepipeline/codebuild-github-tag/infra'
  - './codepipeline/docker-build/infra'
  - './codepipeline/vulnerability-scan/infra'
  - './node-sign-v4'
