packages:
  - './common/cognito-singin/*'
  - './cognito/*'
  - './cognito/authorizer-example/app/*'
  - './cognito/authorizer-example/infra/*'
  - './cognito/cognito-admin/app/*'
  - './cognito/cognito-admin/infra/*'
  - './cognito/next-trpc-example/*'
  - './cognito/next-trpc-example/front/*'
  - './cognito/cognito-saml-next-js/infra/aws/*'
  - './cognito/cognito-saml-next-js/infra/azuread/*'
  - './cognito/cognito-saml-next-js/webapp/*'
  - './cognito/tiny-device-flow/*'
  - './cognito/tiny-device-flow/pages/*'
  - './amplify/*'
  - './amplify/amplify_nextapp/*'
  - './amplify/amplify-cdk/app/*'
  - './amplify/amplify-cdk/infra/*'
  - './cloud9/*'
  - './codebuild/*'
  - './codepipeline/*'
  - './infra/*'
  - './lambda/*'
  - './lambda/apollo-server-api-gateway/*'
  - './lambda/apollo-server-url/*'
  - './lambda/deno-lambda/*'
  - './lambda/eventbridge-lambda/*'
  - './lambda/lambda-examples/*'
  - './lambda/layer/functions/function/*'
  - './lambda/layer/functions/function/handler/*'
  - './lambda/layer/layer/*'
  - './lambda/layer/layer/src/nodejs/*'
  - './node-sign-v4/*'

