packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true
engineStrict: true
strictPeerDependencies: false

overrides:
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
