packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true

engineStrict: true

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  jsondiffpatch@<0.7.2: '>=0.7.2'

strictPeerDependencies: false
