packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true

engineStrict: true

overrides:
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  fast-xml-parser@<5.3.8: '>=5.3.8'
  fast-xml-parser@>=4.1.3 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'

strictPeerDependencies: false
