packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'

engineStrict: true

### https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31#recommended-npmrc
# https://pnpm.io/next/npmrc#strict-peer-dependencies
strictPeerDependencies: false

### https://thedaviddias.dev/notes/how-to-fix-post-pre-build-pnpm
enablePrePostScripts: true
