packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true

engineStrict: true

overrides:
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'

strictPeerDependencies: false
