packages:
  - './common/cognito-singin/*'
  - './cognito/*'
  - './cognito/cognito-saml-next-js/webapp/*'
  - './amplify/*'
  - './cloud9/*'
  - './codebuild/*'
  - './codepipeline/*'
  - './infra/*'
  - './lambda/*'
  - './node-sign-v4/*'

