packages:
  - ./**
  - '!**/.next'
  - '!**/cdk.out'
  - '!**/cdk.out/**'
  - '!**/dist'
  - '!**/build'

enablePrePostScripts: true

engineStrict: true

overrides:
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'

strictPeerDependencies: false
