version: 0.2

env:

phases:
  install: 
    commands:
      - npm install -g typescript
      - tsc -v

  # pre_build: 
  #   commands: 

  build: 
    commands:
      - cd app/src && tsc main.ts
      - aws cloudformation package --template cloudformation/template.yml --s3-bucket codepipeline --output-template-file cloudformation/package-template.yml
  
  artifacts:
    files:
      - app/src/*.js
      - cloudformation/package-template.yml
    discard-paths: no
