version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12

    commands:
      - npm install -g typescript
      - tsc -v

  build: 
    commands:
      - cd typescript-code-build/app/src && tsc main.ts
      - cd ../../ && aws cloudformation package --template cloudformation/template.yml --s3-bucket ${ARTIFACT_STORE} --output-template-file package-template.yml
  
artifacts:
  files:
    - app/src/*.js
    - package-template.yml
  discard-paths: no
  base-directory: typescript-code-build

