AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Repo:
    Type: String
    Default: aws-example
  Owner:
    Type: String
    Default: poad
  Branch:
    Type: String
    Default: master
  OAuthToken:
    NoEcho: true
    Type: String
  LambdaFunctionName:
    Type: String
    Default: hello-typescript

Resources:
  LambdaCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        -
          Action: 
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Action:
                  - s3:PutObject
                  - s3:GetBucketPolicy
                  - s3:GetObject
                  - s3:ListBucket
                Effect: Allow
                Resource: '*'
              - 
                Action:
                  - lambda:UpdateFunctionCode
                Effect: Allow
                Resource: !Join [ ":", [ 'arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', '*' ] ]
              - 
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
                

  LambdaCodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Name: !Join [ "-", [ lambda, !Ref 'AWS::AccountId' ] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL 
        Image: 'aws/codebuild/standard:3.0'
      ServiceRole: !GetAtt LambdaCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: typescript-code-build/buildspec.yml

  LambdaCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: 
             - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - s3:PutObject
                Effect: Allow
                Resource: 
                  - "arn:aws:s3:::*"
              -
                Action:
                  - codepipeline:*
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - cloudformation:Describe*
                  - cloudFormation:List*
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Effect: Allow
                Resource: '*'

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: 
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: 
             - cloudformation.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:ListRoles
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetRole
                  - cloudformation:Describe*
                  - cloudFormation:List*
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Effect: Allow
                Resource: '*'
              -
                Action:
                  - lambda:*
                Effect: Allow
                Resource: !Join [ ":", [ 'arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', '*' ] ]
              -
                Action:
                  - lambda:*
                Effect: Allow
                Resource: '*'

  LambdaBuildCodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub '${LambdaFunctionName}-deploy'
      ArtifactStore: 
        Location: !Sub 'codepipeline-artifact-store-${AWS::Region}-${AWS::AccountId}'
        Type: S3
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt LambdaCodePipelineRole.Arn
      Stages:
        -
          Name: Source
          Actions: 
            -
              Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              InputArtifacts: []
              OutputArtifacts:
                - Name: LambdaSource
              Configuration:
                Owner: !Ref Owner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref OAuthToken
              RunOrder: 1
        -
          Name: Build
          Actions:
            - 
              Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: LambdaSource
              OutputArtifacts:
                - Name: BuildResult
              Configuration:
                ProjectName: !Ref LambdaCodeBuildProject
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            - 
              Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildResult
              OutputArtifacts:
                - Name: LambdaStackResult
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: lambda-change-set
                StackName: !Sub '${LambdaFunctionName}'
                RoleArn: !GetAtt CloudFormationRole.Arn
                TemplatePath: "BuildResult::package-template.yml"
                Capabilities: CAPABILITY_IAM
                OutputFileName: CreateChangeSetOutput.json
                ParameterOverrides: !Sub |
                    {
                      "FunctionName": "${LambdaFunctionName}"
                    }
              RunOrder: 1
            - 
              Name: ApplyChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildResult
              OutputArtifacts:
                - Name: LambdaStackResult2
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: lambda-change-set
                StackName: !Sub '${LambdaFunctionName}'
                RoleArn: !GetAtt CloudFormationRole.Arn
                Capabilities: CAPABILITY_IAM
                OutputFileName: CreateChangeSetOutput2.json
              RunOrder: 2


