AWSTemplateFormatVersion: 2010-09-09

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        -
          Action: 
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Action:
                  - s3:PutObject
                  - s3:GetBucketPolicy
                  - s3:GetObject
                  - s3:ListBucket
                Effect: Allow
                Resource: '*'
              - 
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
              - 
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                Effect: Allow
                Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'
  
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: webhook
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:3.0'
        PrivilegedMode: true
        EnvironmentVariables:
          -
            Name: AWS_DEFAULT_REGION
            Value: !Ref 'AWS::Region'
          -
            Name: AWS_ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
          -
            Name: IMAGE_TAG
            Value: latest
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: GITHUB
        Auth: 
          Type: OAUTH
        Location: !Sub 'https://github.com/poad/aws-example.git'
        BuildSpec: !Sub
          |
            version: 0.2
            phases:
              install:
                runtime-versions:
                  docker: 18
                  python: 3.8
                  java: openjdk11
                commands:
                  - apt update -qq
                  - apt install -qqy --no-install-recommends tree
              build:
                commands:
                  - cd codebuild-webhook-project
                  - ./gradlew clean test
                  - tree
            reports:
              SurefireReports:
                files:
                  - "**/*"
                base-directory: 'codebuild-webhook-project/app/build/test-results'
                discard-paths: no
                file-format: JunitXml
            cache:
              paths:
                - '/root/.gradle/**/*'
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
