checksumBehavior: update

defaultSemverRangePrefix: ""

enableImmutableInstalls: false

enableInlineBuilds: false

enableScripts: true

nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs
