AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  FunctionName:
    Type: String

Resources:
  LamdbaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref FunctionName
      Handler: main.handler
      Runtime: nodejs8.10
      CodeUri: ../app/src
      AutoPublishAlias: test
    
