version: 0.2

batch:
  fast-fail: true

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - env JAVA_HOME=$JAVA_8_HOME JRE_HOME=$JRE_8_HOME JDK_HOME=$JDK_8_HOME sdkmanager "cmdline-tools;latest"
      - PATH="${ANDROID_HOME}/cmdline-tools/bin:${PATH}"
      - export "${PATH}
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew assembleDebug

