version: 0.2

phases:
  install:
    commands:
      - apt-get update -qq
      - DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends curl apt-transport-https gnupg lsb-release
      - curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" > /etc/apt/sources.list.d/trivy.list
      - apt-get update -qq
      - DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends trivy

  build: 
    commands:
      - echo Build started on `date`
      - "docker run --rm goodwithtech/dockle:latest ${SCAN_IMAGE_NAME}"
      - trivy ${SCAN_IMAGE_NAME}

