checksumBehavior: update

defaultSemverRangePrefix: ""

enableImmutableInstalls: false

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.0.cjs
