import type { NextPage } from 'next'
import Head from 'next/head'
import { Amplify } from 'aws-amplify';
import {
  withAuthenticator,
} from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import styles from '../styles/Home.module.css'
import awsconfig from '../aws-config';
import useSession from '../auth/hooks/useSession';
import Fetch from '../fetch/components';
import GraphqlFetch from '../graphql';

Amplify.configure(awsconfig);

interface HomeProps {
  signOut: (opts?: any) => Promise<any>
}

const Home: NextPage<HomeProps> = (props?: HomeProps): JSX.Element => {

  const session = useSession();

  const { signOut } = props || { signOut: () => { } };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={signOut}>Sign out</button>
        </div>

        <div>
          <div><Fetch label="ID token" token={session?.idToken.token}/></div>
        </div>

        <h2>GraphQL</h2>
        <GraphqlFetch />

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default withAuthenticator<HomeProps>(Home, {
  signUpAttributes: [
    'email'
  ]
});
