name: Node.js modules auto update
 
on:
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:
  auto_update:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      if: github.event_name != 'pull_request'
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16.x
        check-latest: true

    - name: update (amplify/amplified_todo)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/amplify/amplified_todo/
        
    - name: update (amplify/amplify_nextapp)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/amplify/amplify_nextapp/

    - name: update (amplify/amplify-cdk/app)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/amplify/amplify-cdk/app/

    - name: update (amplify/amplify-cdk/infra)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/amplify/amplify-cdk/infra/

    - name: update (cloud9)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cloud9/

    - name: update (codebuild/custom-image-test)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codebuild/custom-image-test/

    - name: update (codepipeline/adoptium-temurin-jib/infra/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codepipeline/adoptium-temurin-jib/infra/

    - name: update (codepipeline/codebuild-custom-image/java-adopt-base/infra/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codepipeline/codebuild-custom-image/java-adopt-base/infra/

    - name: update (codepipeline/codebuild-github-tag/infra/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codepipeline/codebuild-github-tag/infra/

    - name: update (codepipeline/docker-build/infra/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codepipeline/docker-build/infra/

    - name: update (codepipeline/vulnerability-scan/infra/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/codepipeline/vulnerability-scan/infra/

    - name: update (cognito/cognito-admin/app)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/cognito-admin/app/

    - name: update (cognito/cognito-admin/infra)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/cognito-admin/infra/

    - name: update (cognito/cognito-saml-next-js/webapp)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/cognito-saml-next-js/webapp/

    - name: update (cognito/cognito-saml-next-js/infra)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/cognito-saml-next-js/infra/

    - name: update (cognito/tiny-device-flow)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/tiny-device-flow/

    - name: update (cognito/tiny-device-flow/pages)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/cognito/tiny-device-flow/pages/

    - name: update (infra/ecs/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/infra/ecs/

    - name: update (infra/s3/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/infra/s3/

    - name: update (lambda/container/sample)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/container/simple/

    - name: update (lambda/apollo-server-url)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/apollo-server-url/

    - name: update (lambda/apollo-server-api-gateway)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/apollo-server-api-gateway/

    - name: update (lambda/eventbridge-lambda)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/eventbridge-lambda/

    - name: update (lambda/container/sample/lambda)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/container/simple/lambda/

    - name: update (lambda/layer/functions/function)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/layer/functions/function/

    - name: update (lambda/layer/functions/function/handler)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/layer/functions/function/handler/

    - name: update (lambda/layer/layer/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/layer/layer/

    - name: update (/lambda/layer/layer/src/nodejs/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/lambda/layer/layer/src/nodejs/

    - name: update (/node-sign-v4/)
      uses: poad/update-node-modules@v1.0.5
      with:
        yarn: true
        path: ${{github.workspace}}/node-sign-v4/

    - name: Commit files
      run: |
        git config --local user.email "ken-yo@mbr.nifty.com"
        git config --local user.name "Kenji Saito"
        TIMESTAMP=$(date)
        BRANCH_NAME="feature/bump-modules-$(date "+%Y%m%d-%H%M%S")"
        git checkout -b "${BRANCH_NAME}"
        if [ $(git diff | wc -l) -eq 0 ]; then
          echo "CHANGE_STATE=no_changed" >> $GITHUB_ENV
          exit 0
        fi
        git add *
        git commit -m "Auto update at ${TIMESTAMP}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
        echo "CHANGE_STATE=changed" >> $GITHUB_ENV
    - name: Push Changes
      if: success() && env.CHANGE_STATE == 'changed'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        branch: ${{ env.BRANCH_NAME }}

    - name: Prepare create pull request
      run: |
        repo=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "REPO_NAME=${repo}" >> $GITHUB_ENV

    - name: Create pull request
      id: create-pull-request
      if: success() && env.CHANGE_STATE == 'changed'
      uses: poad/github-pull-requester@v1.0.1
      with:
        head_branch: ${{ env.BRANCH_NAME }}
        title: ${{ format('Auto update at {0}', env.TIMESTAMP) }}
        body: ${{ format('Update the modules at {0}', env.TIMESTAMP) }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ env.REPO_NAME }}
        owner: ${{ github.repository_owner }}

    - name: Extract response
      env:
        RESULT: ${{ steps.create-pull-request.outputs.result }}
        RESULT_JSON: ${{ toJSON(steps.create-pull-request.outputs.result) }}
      run: |
        PULL_REQUEST_HTML_URL=$(echo ${RESULT} | jq -r .data.html_url)
        echo "PULL_REQUEST_HTML_URL=${PULL_REQUEST_HTML_URL}" >> $GITHUB_ENV
        PULL_REQUEST_NUMBER=$(echo ${RESULT} | jq -r .data.number)
        echo "PULL_REQUEST_NUMBER=${PULL_REQUEST_NUMBER}" >> $GITHUB_ENV
        PULL_REQUEST_ID=$(echo ${RESULT} | jq -r .data.node_id)
        echo "PULL_REQUEST_ID=${PULL_REQUEST_ID}" >> $GITHUB_ENV

    - name: Send result with Pull Request
      if: success() && env.CHANGE_STATE == 'changed' && github.event_name != 'pull_request'
      uses: slackapi/slack-github-action@v1.22
      with:
        payload: "{ \"text\": \"${{ env.SLACKK_PAYLOAD }}\" }"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACKK_PAYLOAD: ${{ format('{0} {1}\nPull Request <{2}>', github.workflow, job.status, env.PULL_REQUEST_HTML_URL) }}

    - name: Send result without Pull Request
      if: success() && env.CHANGE_STATE == 'changed' && github.event_name != 'pull_request'
      uses: slackapi/slack-github-action@v1.22
      with:
        payload: "{ \"text\": \"${{ env.SLACKK_PAYLOAD }}\" }"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACKK_PAYLOAD: ${{ format('{0} {1}', github.workflow, job.status) }}
      
    - name: Pull request auto merge enabler
      if: success() && env.CHANGE_STATE == 'changed' && github.actor != 'dependabot[bot]'
      uses: poad/github-pull-request-auto-merge-enable-action@v1.0.2
      with:
        pull_request_id: ${{ env.PULL_REQUEST_ID }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH
