name: Java CI

on:
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: zulu

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle (lambda/cognito-console/client/DeviceFlowExample)
      env:
        OAUTH_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
        COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
      run: |
        cd lambda/cognito-console/client/DeviceFlowExample
        rm -rf app/src/main/res/raw/example_oauth.json
        echo $(cat oauth.json.template) > app/src/main/res/raw/oauth.json
        chmod +x gradlew
        ./gradlew build

