name: Hadolint

on:
  schedule:
    - cron:  '0 15 * * *'

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:
  hadolint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pattern: [
          { app: hello-rust-lambda, image: lambda },
          { app: simple, image: lambda-simple },
        ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}

    - name: Build (debug) lambda/container/${{ matrix.pattern.app }}/lambda
      run: |
        docker build --rm \
          --build-arg NODE_VERSION=14 \
          --build-arg DIST=debian \
          -t ${{ matrix.pattern.image }}:latest \
          lambda/container/${{ matrix.pattern.app }}/lambda

    - name: Build (release) lambda/container/${{ matrix.pattern.app }}/lambda
      run: |
        docker build --rm \
          --build-arg NODE_VERSION=14 \
          --build-arg DIST=debian \
          --target=release \
          -t ${{ matrix.pattern.image }}:release \
          lambda/container/${{ matrix.pattern.app }}/lambda

    - name: Hadolint lambda/container/${{ matrix.pattern.app }}/lambda
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: lambda/container/${{ matrix.pattern.app }}/lambda/Dockerfile
  